In [1]:
import pandas as pd
import numpy as np

# read csv file
data = pd.read_csv("/home/parham//Desktop/project/Housing/Housing/posts.csv")
# create dataframe
df = pd.DataFrame(data=data)
df


Zone  Price Years  Rooms  Area NumberOfElevators floor direction
0       کامرانیه     8400     3      2   120                 1     5     شمالی
1        میرداماد    5928     0      2    80                 1     3       NaN
2        پاسداران    4450     0      1    68                 1     1       NaN
3        شمس آباد       6     0      2   120                 1     2       NaN
4       تهرانپارس     NaN     0      2   104                 1     2       NaN
...            ...    ...   ...    ...   ...               ...   ...       ...
4501     زعفرانیه   16200     1      3   180                 0   NaN       NaN
4502        ولنجک   18414     4      3   198                 0   NaN       NaN
4503        ولنجک   21850     2      3   230                 0   NaN       NaN
4504        ولنجک      37     0      4   320                 0   NaN       NaN
4505      محمودیه   18500     5      3   200                 0   NaN       NaN

[4506 rows x 8 columns]

In [2]:
### Lets clean the data
df=df.dropna(subset = ['Price']) # drop the rows that the target value has not any value.
df.index = range(0,df.shape[0]) # re index the dataframe
#################################################################
#################################################################
### convert numeric string to int or float:

#    ### convert Price column to float value
df["Price"] = df["Price"].str.replace(",","")
df["Price"] = df["Price"].astype(float)

price= df["Price"]
#Some of data prices are like 8400.0 but some of them are like 6.0 or 37.0 How ever both of them shold be represent in scale of billion Toman so I re-scale all of data As bellow.
for i in range(0,len(price)):
    if price[i] > 100.0:
        price[i] = price[i]/1000

df

<ipython-input-2-2ae1b4534b42>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"] = df["Price"].str.replace(",","")
<ipython-input-2-2ae1b4534b42>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"] = df["Price"].astype(float)
<ipython-input-2-2ae1b4534b42>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Zone   Price Years  Rooms  Area NumberOfElevators floor direction
0      کامرانیه     8.400     3      2   120                 1     5     شمالی
1       میرداماد    5.928     0      2    80                 1     3       NaN
2       پاسداران    4.450     0      1    68                 1     1       NaN
3       شمس آباد    6.000     0      2   120                 1     2       NaN
4            ظفر    7.700     8      3   131                 1     1       NaN
...           ...     ...   ...    ...   ...               ...   ...       ...
4465    زعفرانیه   16.200     1      3   180                 0   NaN       NaN
4466       ولنجک   18.414     4      3   198                 0   NaN       NaN
4467       ولنجک   21.850     2      3   230                 0   NaN       NaN
4468       ولنجک   37.000     0      4   320                 0   NaN       NaN
4469     محمودیه   18.500     5      3   200                 0   NaN       NaN

[4470 rows x 8 columns]

In [3]:
# finding how many data are null
isnull = df['Years'].isnull()
isnull = list(isnull) 

# converting those records in "Years" column which are string,NoneType and integer to float type
for i in range(0,len(df['Years'])):
    if df['Years'][i] == '—':
        
        df['Years'][i] = None
    if type(df['Years'][i])==float or type(df['Years'][i])==int or type(df['Years'][i])==str: 
        if isnull[i] == False and (df['Years'][i] is not None or df['Years'][i]!= np.nan): 
            
            df['Years'][i]= int(df['Years'][i])
    else:
        
        df['Years'][i]= None
for i in range(0,len(df['Years'])):
    if df['Years'][i]== None:
        print(i,"   " ,df['Years'][i])
        df['Years'][i]= np.nan

<ipython-input-3-f0a267d1ae7d>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Years'][i]= int(df['Years'][i])
/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3437: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
<ipython-input-3-f0a267d1ae7d>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Years'][i] = None
<ipython-input-3

In [4]:
#converting string records for Rooms and Area column to integer
df["Rooms"] = df["Rooms"].astype(int)	
df["Area"] = df["Area"].astype(int)	

<ipython-input-4-232976a58402>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Rooms"] = df["Rooms"].astype(int)
<ipython-input-4-232976a58402>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Area"] = df["Area"].astype(int)


In [5]:
# converting those records in "NumberOfElevators" column which are string,NoneType to integer type
for i in range(0,len(df['NumberOfElevators'])):
    if df['NumberOfElevators'][i] == '-':
        df['NumberOfElevators'][i] = None
    if df['NumberOfElevators'][i] =='دارد':
        df['NumberOfElevators'][i] = 1
    

    if type(df['NumberOfElevators'][i])== str :
        
        df['NumberOfElevators'][i]= int(df['NumberOfElevators'][i])
    if type(df['NumberOfElevators'][i]) == int:
        pass
    else:
        
        df['NumberOfElevators'][i] = 0
    

<ipython-input-5-e86f992ebaad>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NumberOfElevators'][i]= int(df['NumberOfElevators'][i])
<ipython-input-5-e86f992ebaad>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NumberOfElevators'][i] = None
<ipython-input-5-e86f992ebaad>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NumberOfElevators'][i] = 0
<ipython-input-5-e86f992ebaad>:6: SettingWithCopyWarning: 
A value is tr

In [6]:
import math
import numpy as np
# converting those records in "floor" column which are string,NoneType to integer type
isnull = df['floor'].isnull()
isnull = list(isnull)    
for i in range(0,len(df['floor'])):
    if df['floor'][i] == '-':
        df['floor'][i] = None
    if df['floor'][i] == 'دارد':
        df['floor'][i] = 1
        
    if type(df['floor'][i])==float or type(df['floor'][i])==int or type(df['floor'][i])==str: 
        if isnull[i] == False: 
            df['floor'][i]= int(df['floor'][i])
    

    else:
        df['floor'][i] = None
for i in range(0,len(df['floor'])):
    if df['floor'][i] == None:
        df['floor'][i] = np.nan

<ipython-input-6-7c7fb8b8c569>:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['floor'][i]= int(df['floor'][i])
<ipython-input-6-7c7fb8b8c569>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['floor'][i] = None
<ipython-input-6-7c7fb8b8c569>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['floor'][i] = None
<ipython-input-6-7c7fb8b8c569>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a D

In [7]:
### Dealing with missed values
df.isnull().sum()

Zone                    2
Price                   0
Years                  10
Rooms                   0
Area                    0
NumberOfElevators       0
floor                 361
direction            3928
dtype: int64

In [8]:
## As we can see we have 3928 values missed in direction column(more than half of the data) so we drop the column
df = df.loc[ : ].drop(['direction'],axis=1)
df

Zone   Price Years  Rooms  Area NumberOfElevators floor
0      کامرانیه     8.400     3      2   120                 1     5
1       میرداماد    5.928     0      2    80                 1     3
2       پاسداران    4.450     0      1    68                 1     1
3       شمس آباد    6.000     0      2   120                 1     2
4            ظفر    7.700     8      3   131                 1     1
...           ...     ...   ...    ...   ...               ...   ...
4465    زعفرانیه   16.200     1      3   180                 0   NaN
4466       ولنجک   18.414     4      3   198                 0   NaN
4467       ولنجک   21.850     2      3   230                 0   NaN
4468       ولنجک   37.000     0      4   320                 0   NaN
4469     محمودیه   18.500     5      3   200                 0   NaN

[4470 rows x 7 columns]

In [9]:
import pandas as pd
from sklearn.impute import SimpleImputer
data = df[['floor', 'Price']]
data
imp = SimpleImputer(strategy="most_frequent")
imp = imp.fit_transform(data)
for i in range(0,len(imp)):
    df['floor'][i] = imp[i][0]
    

<ipython-input-9-51e21d710222>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['floor'][i] = imp[i][0]


In [10]:
import pandas as pd
from sklearn.impute import SimpleImputer
data = df[['Years', 'Price']]
data
imp = SimpleImputer(strategy="most_frequent")
imp = imp.fit_transform(data)
for i in range(0,len(imp)):
    df['Years'][i] = imp[i][0]
    

<ipython-input-10-8ddc842711d3>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Years'][i] = imp[i][0]


In [11]:
import pandas as pd
from sklearn.impute import SimpleImputer
data = df[['Zone', 'Price']]
data
imp = SimpleImputer(strategy="most_frequent")
imp = imp.fit_transform(data)
for i in range(0,len(imp)):
    df['Zone'][i] = imp[i][0]

<ipython-input-11-e32e8c0e1c89>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Zone'][i] = imp[i][0]


In [12]:
df

Zone   Price Years  Rooms  Area NumberOfElevators floor
0      کامرانیه     8.400     3      2   120                 1     5
1       میرداماد    5.928     0      2    80                 1     3
2       پاسداران    4.450     0      1    68                 1     1
3       شمس آباد    6.000     0      2   120                 1     2
4            ظفر    7.700     8      3   131                 1     1
...           ...     ...   ...    ...   ...               ...   ...
4465    زعفرانیه   16.200     1      3   180                 0     3
4466       ولنجک   18.414     4      3   198                 0     3
4467       ولنجک   21.850     2      3   230                 0     3
4468       ولنجک   37.000     0      4   320                 0     3
4469     محمودیه   18.500     5      3   200                 0     3

[4470 rows x 7 columns]

In [13]:
df.isnull().sum()

Zone                 0
Price                0
Years                0
Rooms                0
Area                 0
NumberOfElevators    0
floor                0
dtype: int64

In [14]:
data = df
data['Zone'].value_counts()

  میرداماد               521
  ظفر                    419
  قیطریه                 400
  پاسداران               329
  اختیاریه               312
                        ... 
  خانه گستر                1
  جهاد                     1
  امام خمینی               1
 مدرن کامرانیه شمالی       1
 محمودیه                   1
Name: Zone, Length: 195, dtype: int64

In [15]:
# Some records for Zone column are not an Area in Tehran such as 'گلسار' so 
#I create a list of district for Tehran and Also translate each Zone to English. 
InTehran = [('الهیه','Elahie'),('نیاوران','Niavaran'),('جلفا','Jolfa'),('دیباجی','Dibaji'),
('دولت','Dowlat'),('تهرانپارس','Tehran_pars'),
('بوکان','Bukan'),('قلهک','Qolhak'),('جمشیدیه','Jamshidieh'),('سید خندان','Sed_Khandan'),
('اقدسیه','Aqdasieh'),('اندرزگو','Andarzgu'),('دزاشیب','Dezashib'),('نبرد','Nabard'),
('نیروی هوایی','Niru_havai'),('ونک','Vanak'),('مهران','Mehran'),('زعفرانیه','Zaferanieh'),
('اختیاریه','Ekhtiarieh'),('فرمانیه','Farmanieh'),('هروی','Heravi'),('قیطریه','Qeitarieh'),
('ولنجک','Velenjak'),('میرداماد','Mirdamad'),('کامرانیه','Kamranieh'),
('پاسداران','Pasdaran'),('ظفر','Zafar'),('شمس آباد','ShamsAbad')]


In [16]:
# translation of each Zone in Tehran and assigning None type value to those which are not in Tehran(I plan to remove these record)
for i in range(0,len(data['Zone'])):
    if InTehran[0][0] in df['Zone'][i]:    
        df['Zone'][i]= InTehran[0][1]
    elif InTehran[1][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[1][1]
    elif InTehran[2][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[2][1]
    elif InTehran[3][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[3][1]
    elif InTehran[4][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[4][1]
    elif InTehran[5][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[5][1]
    elif InTehran[6][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[6][1]
    elif InTehran[7][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[7][1]
    elif InTehran[8][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[8][1]
    elif InTehran[9][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[9][1]
    elif InTehran[10][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[10][1]
    elif InTehran[11][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[11][1]
    elif InTehran[12][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[12][1]
    elif InTehran[13][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[13][1]
    elif InTehran[14][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[14][1]
    elif InTehran[15][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[15][1]
    elif InTehran[16][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[16][1]
    elif InTehran[17][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[17][1]
    elif InTehran[18][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[18][1]
    elif InTehran[19][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[19][1]
    elif InTehran[20][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[20][1]
    elif InTehran[21][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[21][1]
    elif InTehran[22][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[22][1]
    elif InTehran[23][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[23][1]
    elif InTehran[24][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[24][1]
    elif InTehran[25][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[25][1]
    elif InTehran[26][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[26][1]
    elif InTehran[27][0] in df['Zone'][i]:
        df['Zone'][i]= InTehran[27][1]
    
    else:
        df['Zone'][i]= None

for i in range(0,len(df['Zone'])):
    if df['Zone'][i] == None:
        df['Zone'][i] = np.nan
df=df.dropna(subset = ['Zone']) # drop the rows that the target value has not any value.
df.index = range(0,df.shape[0]) # re index the dataframe

<ipython-input-16-be7cfc8abb45>:52: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Zone'][i]= InTehran[24][1]
<ipython-input-16-be7cfc8abb45>:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Zone'][i]= InTehran[23][1]
<ipython-input-16-be7cfc8abb45>:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Zone'][i]= InTehran[25][1]
<ipython-input-16-be7cfc8abb45>:58: SettingWithCopyWarning: 
A value is trying to be set on a copy o

In [17]:
data['Zone'].value_counts()

Mirdamad       521
Zafar          419
Qeitarieh      411
Pasdaran       329
Ekhtiarieh     312
Zaferanieh     267
Heravi         231
Dowlat         227
Farmanieh      165
Dibaji         124
Niavaran       100
Qolhak          95
Tehran_pars     94
Velenjak        92
Jolfa           73
Mehran          44
Elahie          39
Nabard          35
Vanak           35
Kamranieh       30
Aqdasieh        26
Dezashib        24
ShamsAbad       15
Niru_havai      14
Sed_Khandan     14
Jamshidieh       9
Andarzgu         7
Bukan            6
Name: Zone, dtype: int64

In [18]:
zone = pd.get_dummies(df['Zone'], prefix='Zone')
df=df.drop(columns=['Zone'])
data = pd.concat([zone,df],axis=1)
data.head()

Zone_Andarzgu  Zone_Aqdasieh  Zone_Bukan  Zone_Dezashib  Zone_Dibaji  \
0              0              0           0              0            0   
1              0              0           0              0            0   
2              0              0           0              0            0   
3              0              0           0              0            0   
4              0              0           0              0            0   

   Zone_Dowlat  Zone_Ekhtiarieh  Zone_Elahie  Zone_Farmanieh  Zone_Heravi  \
0            0                0            0               0            0   
1            0                0            0               0            0   
2            0                0            0               0            0   
3            0                0            0               0            0   
4            0                0            0               0            0   

   ...  Zone_Vanak  Zone_Velenjak  Zone_Zafar  Zone_Zaferanieh  Price  Years  \
0  ...           0              0           0                0  8.400      3   
1  ...           0              0           0                0  5.928      0   
2  ...           0              0           0                0  4.450      0   
3  ...           0              0           0                0  6.000      0   
4  ...           0              0           1                0  7.700      8   

   Rooms  Area  NumberOfElevators  floor  
0      2   120                  1      5  
1      2    80                  1      3  
2      1    68                  1      1  
3      2   120                  1      2  
4      3   131                  1      1  

[5 rows x 34 columns]

In [19]:
from sklearn.preprocessing import KBinsDiscretizer
# kbins is created
kbins = KBinsDiscretizer(n_bins=6, encode='ordinal', strategy='quantile')
# target feature is Discretized
df_y = pd.DataFrame(
    kbins.fit_transform(data[['Price']]), 
    columns=['Price']
)
df_y

Price
0       3.0
1       1.0
2       0.0
3       1.0
4       2.0
...     ...
3753    5.0
3754    5.0
3755    5.0
3756    5.0
3757    5.0

[3758 rows x 1 columns]

In [20]:
# re construct the data frame
data=data.drop(columns=['Price'])
data = pd.concat([data,df_y],axis=1)
data

Zone_Andarzgu  Zone_Aqdasieh  Zone_Bukan  Zone_Dezashib  Zone_Dibaji  \
0                 0              0           0              0            0   
1                 0              0           0              0            0   
2                 0              0           0              0            0   
3                 0              0           0              0            0   
4                 0              0           0              0            0   
...             ...            ...         ...            ...          ...   
3753              0              0           0              0            0   
3754              0              0           0              0            0   
3755              0              0           0              0            0   
3756              0              0           0              0            0   
3757              0              0           0              0            0   

      Zone_Dowlat  Zone_Ekhtiarieh  Zone_Elahie  Zone_Farmanieh  Zone_Heravi  \
0               0                0            0               0            0   
1               0                0            0               0            0   
2               0                0            0               0            0   
3               0                0            0               0            0   
4               0                0            0               0            0   
...           ...              ...          ...             ...          ...   
3753            0                0            0               0            0   
3754            0                0            0               0            0   
3755            0                0            0               0            0   
3756            0                0            0               0            0   
3757            0                0            0               0            0   

      ...  Zone_Vanak  Zone_Velenjak  Zone_Zafar  Zone_Zaferanieh  Years  \
0     ...           0              0           0                0      3   
1     ...           0              0           0                0      0   
2     ...           0              0           0                0      0   
3     ...           0              0           0                0      0   
4     ...           0              0           1                0      8   
...   ...         ...            ...         ...              ...    ...   
3753  ...           0              0           0                1      2   
3754  ...           0              0           0                1      1   
3755  ...           0              1           0                0      4   
3756  ...           0              1           0                0      2   
3757  ...           0              1           0                0      0   

      Rooms  Area  NumberOfElevators  floor  Price  
0         2   120                  1      5    3.0  
1         2    80                  1      3    1.0  
2         1    68                  1      1    0.0  
3         2   120                  1      2    1.0  
4         3   131                  1      1    2.0  
...     ...   ...                ...    ...    ...  
3753      3   225                  0      3    5.0  
3754      3   180                  0      3    5.0  
3755      3   198                  0      3    5.0  
3756      3   230                  0      3    5.0  
3757      4   320                  0      3    5.0  

[3758 rows x 34 columns]

In [21]:
# split the data frame into train set and test set
from sklearn.model_selection import train_test_split
import sklearn

x_feature=data.loc[ : , data.columns !='Price']
y_feature=data['Price']
x_train,x_test,y_train,y_test = train_test_split(x_feature,y_feature,test_size=0.25,random_state=0)


In [22]:
# Model Selection:

# SVM:
from sklearn import svm
clf_svm = svm.SVC()  #create svm classifier
clf_svm.fit(x_train, y_train) # learning
# prediction process
SvmPrediction=clf_svm.predict(x_test) #prediction


In [23]:
#Evaluation:

from sklearn.metrics import classification_report,confusion_matrix
y_true = y_test 
y_pred = SvmPrediction
#create confusion_matrix
print(confusion_matrix(y_true, y_pred))
# create classes for classification
target_names = ['class 0','class 1','class 2','class 3','class 4','class 5']
#report the classification parameter 
print(classification_report(y_true, y_pred, target_names=target_names))
# computing Train Accuracy and Test Accuracy 
print(f'Train Accuracy : {clf_svm.score(x_train,y_train):3f}')
print(f'Test Accuracy : {clf_svm.score(x_test,y_test):3f}')

[[ 74  40  14   9   7  12]
 [ 23 100  33   6   2   0]
 [  2  31  91  32   1   0]
 [  0   4  40  66  27   9]
 [  1   0   1  36  85  24]
 [  0   0   2   1  32 135]]
              precision    recall  f1-score   support

     class 0       0.74      0.47      0.58       156
     class 1       0.57      0.61      0.59       164
     class 2       0.50      0.58      0.54       157
     class 3       0.44      0.45      0.45       146
     class 4       0.55      0.58      0.56       147
     class 5       0.75      0.79      0.77       170

    accuracy                           0.59       940
   macro avg       0.59      0.58      0.58       940
weighted avg       0.60      0.59      0.59       940

Train Accuracy : 0.590490
Test Accuracy : 0.586170


In [24]:
# Tuning Hyper-parameter (Greedy search):
from sklearn.model_selection import GridSearchCV
tuned_parameters = {
    'kernel':('linear','poly','rbf','sigmoid'),
    
}
clf_svm=svm.SVC() # create classifier
# estimate the best set of hyper-parameter
svm_cv= GridSearchCV(clf_svm,tuned_parameters, cv=5, verbose=True)  
svm_cv.fit(x_train, y_train)
svm_cv.best_estimator_

Fitting 5 folds for each of 4 candidates, totalling 20 fits


SVC(kernel='linear')

In [25]:
# calcuating Accuracy with best hyper-parameter:
clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(x_train, y_train)
# prediction process
SvmPrediction = clf_svm.predict(x_test)
y_true = y_test
y_pred = SvmPrediction
print(confusion_matrix(y_true, y_pred))
target_names = ['class 0','class 1','class 2','class 3','class 4','class 5']
print(classification_report(y_true, y_pred, target_names=target_names))
print(f'Train Accuracy : {clf_svm.score(x_train,y_train):3f}')
print(f'Test Accuracy : {clf_svm.score(x_test,y_test):3f}')

[[ 87  35   9   5   6  14]
 [ 54  80  27   2   1   0]
 [  8  19  96  31   3   0]
 [  2   1  22  97  21   3]
 [  3   1   1  19 104  19]
 [  1   0   2   0  22 145]]
              precision    recall  f1-score   support

     class 0       0.56      0.56      0.56       156
     class 1       0.59      0.49      0.53       164
     class 2       0.61      0.61      0.61       157
     class 3       0.63      0.66      0.65       146
     class 4       0.66      0.71      0.68       147
     class 5       0.80      0.85      0.83       170

    accuracy                           0.65       940
   macro avg       0.64      0.65      0.64       940
weighted avg       0.64      0.65      0.64       940

Train Accuracy : 0.650461
Test Accuracy : 0.647872


In [26]:
# Cross validation score:
from sklearn.model_selection import cross_val_score 
clf_svm = svm.SVC(coef0=0.001, gamma=20, kernel='linear')
scores = cross_val_score(clf_svm, x_train, y_train, cv=5)

print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.63 (+/- 0.06)


In [27]:
# Ensemble Method(Random_forest):
from sklearn.ensemble import RandomForestClassifier
#create the classifier
ens_classifier = RandomForestClassifier(max_depth=2)
ens_classifier.fit(x_train, y_train) #learning
EnsPrediction=ens_classifier.predict(x_test) #prediction

In [28]:
# Evaluation:
y_true = y_test         
y_pred = EnsPrediction   
#create confusion_matrix
print(confusion_matrix(y_true, y_pred))
# create classes for classification
target_names = ['class 0','class 1','class 2','class 3','class 4','class 5']
#report the classification parameter 
print(classification_report(y_true, y_pred, target_names=target_names))
## computing Train Accuracy and Test Accuracy 
print(f'Train Accuracy : {ens_classifier.score(x_train,y_train):3f}')
print(f'Test Accuracy : {ens_classifier.score(x_test,y_test):3f}')

[[119   1  11   6   6  13]
 [100   3  40  17   2   2]
 [ 36   9  67  38   7   0]
 [  5   2  45  34  45  15]
 [  1   0   4  10  93  39]
 [  1   0   1   1  11 156]]
              precision    recall  f1-score   support

     class 0       0.45      0.76      0.57       156
     class 1       0.20      0.02      0.03       164
     class 2       0.40      0.43      0.41       157
     class 3       0.32      0.23      0.27       146
     class 4       0.57      0.63      0.60       147
     class 5       0.69      0.92      0.79       170

    accuracy                           0.50       940
   macro avg       0.44      0.50      0.45       940
weighted avg       0.44      0.50      0.45       940

Train Accuracy : 0.516678
Test Accuracy : 0.502128


In [29]:
# Tuning Hyper-parameter (Greedy search):

from sklearn.model_selection import GridSearchCV
tuned_parameters = {
    'n_estimators':[10,100],
    'max_features':('auto', 'sqrt','log2'),
    'bootstrap':(True, False),
    'max_depth':[2,100],
}
ens_classifier=RandomForestClassifier() # create classifier
# estimate the best set of hyper-parameter
ens_cv= GridSearchCV(ens_classifier,tuned_parameters, cv=3, verbose=2,n_jobs=4) 



ens_cv.fit(x_train, y_train)
ens_cv.best_estimator_

Fitting 3 folds for each of 24 candidates, totalling 72 fits


RandomForestClassifier(max_depth=100)

In [30]:
# calcuating Accuracy with best hyper-parameter:

ens_classifier = RandomForestClassifier(max_depth=100, max_features='log2')
ens_classifier.fit(x_train, y_train) #learning
EnsPrediction=ens_classifier.predict(x_test) #prediction

In [31]:
y_true = y_test 
y_pred = EnsPrediction
#create confusion_matrix
print(confusion_matrix(y_true, y_pred))
# create classes for classification
target_names = ['class 0','class 1','class 2','class 3','class 4','class 5']
#report the classification parameter 
print(classification_report(y_true, y_pred, target_names=target_names))
# computing Train Accuracy and Test Accuracy 
print(f'Train Accuracy : {ens_classifier.score(x_train,y_train):3f}')
print(f'Test Accuracy : {ens_classifier.score(x_test,y_test):3f}')

[[109  16   4   9   6  12]
 [ 20 112  25   5   2   0]
 [  4  14 115  20   4   0]
 [  1   2  10 117  15   1]
 [  0   1   4   9 118  15]
 [  2   1   1   1  16 149]]
              precision    recall  f1-score   support

     class 0       0.80      0.70      0.75       156
     class 1       0.77      0.68      0.72       164
     class 2       0.72      0.73      0.73       157
     class 3       0.73      0.80      0.76       146
     class 4       0.73      0.80      0.77       147
     class 5       0.84      0.88      0.86       170

    accuracy                           0.77       940
   macro avg       0.77      0.77      0.76       940
weighted avg       0.77      0.77      0.77       940

Train Accuracy : 0.969127
Test Accuracy : 0.765957


In [32]:
from sklearn.model_selection import cross_val_score 
ens_classifier = RandomForestClassifier(max_depth=100, max_features='log2')
scores = cross_val_score(ens_classifier, x_train, y_train, cv=3)

print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.73 (+/- 0.03)


In [33]:
# MLP model:
from sklearn.neural_network import MLPClassifier

#create a classifier
MLP_clf = MLPClassifier()
MLP_clf.fit(x_train, y_train)
MLPPrediction=MLP_clf.predict(x_test)

In [34]:
# Evaluation:
y_true = y_test         
y_pred = MLPPrediction   
#create confusion_matrix
print(confusion_matrix(y_true, y_pred))

# create classes for classification
target_names = ['class 0','class 1','class 2','class 3','class 4','class 5']
#report the classification parameter 
print(classification_report(y_true, y_pred, target_names=target_names))
print(f'Train Accuracy : {ens_classifier.score(x_train,y_train):3f}')
print(f'Test Accuracy : {ens_classifier.score(x_test,y_test):3f}')

[[ 99  25   7   3   6  16]
 [ 38  90  33   1   2   0]
 [  3  23 110  14   7   0]
 [ 10   2  46  47  37   4]
 [  1   0   4  10  99  33]
 [  1   0   2   0  12 155]]
              precision    recall  f1-score   support

     class 0       0.65      0.63      0.64       156
     class 1       0.64      0.55      0.59       164
     class 2       0.54      0.70      0.61       157
     class 3       0.63      0.32      0.43       146
     class 4       0.61      0.67      0.64       147
     class 5       0.75      0.91      0.82       170

    accuracy                           0.64       940
   macro avg       0.64      0.63      0.62       940
weighted avg       0.64      0.64      0.63       940



NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [35]:
# Tuning Hyper-parameter (Greedy search):
from sklearn.model_selection import GridSearchCV
tuned_parameters = {
    'hidden_layer_sizes': [(10,30,10),(20,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
    
}

MLP_classifier=MLPClassifier() # create classifier
# estimate the best set of hyper-parameter
MLP_cv= GridSearchCV(MLP_classifier,tuned_parameters, cv=3) 

MLP_cv.fit(x_train, y_train)
MLP_cv.best_estimator_

/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't 

MLPClassifier(activation='tanh', hidden_layer_sizes=(10, 30, 10),
              learning_rate='adaptive')

In [36]:
# calcuating Accuracy with best hyper-parameter:
MLP_clf = MLPClassifier(activation='tanh', alpha=0.05, hidden_layer_sizes=(10, 30, 10))
MLP_clf.fit(x_train, y_train)
MLPPrediction=MLP_clf.predict(x_test)

In [37]:
y_true = y_test         
y_pred = MLPPrediction   
#create confusion_matrix
print(confusion_matrix(y_true, y_pred))
# create classes for classification
target_names = ['class 0','class 1','class 2','class 3','class 4','class 5']
#report the classification parameter 
print(classification_report(y_true, y_pred, target_names=target_names))
# computing Train Accuracy and Test Accuracy 
print(f'Train Accuracy : {MLP_clf.score(x_train,y_train):3f}')
print(f'Test Accuracy : {MLP_clf.score(x_test,y_test):3f}')

[[ 88  35   8   5   8  12]
 [ 17 112  32   2   1   0]
 [  1  20 100  35   1   0]
 [  0   2  21 100  22   1]
 [  1   0   4  30 106   6]
 [  0   1   2   1  28 138]]
              precision    recall  f1-score   support

     class 0       0.82      0.56      0.67       156
     class 1       0.66      0.68      0.67       164
     class 2       0.60      0.64      0.62       157
     class 3       0.58      0.68      0.63       146
     class 4       0.64      0.72      0.68       147
     class 5       0.88      0.81      0.84       170

    accuracy                           0.69       940
   macro avg       0.70      0.68      0.68       940
weighted avg       0.70      0.69      0.69       940

Train Accuracy : 0.721789
Test Accuracy : 0.685106


In [35]:
from sklearn.model_selection import cross_val_score 
MLP_clf = MLPClassifier(activation='tanh', alpha=0.05, hidden_layer_sizes=(10, 30, 10))
scores = cross_val_score(MLP_clf, x_train, y_train, cv=3)

print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
Accuracy: 0.69 (+/- 0.02)
/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [38]:

from sklearn.tree import DecisionTreeClassifier
dt_clf= DecisionTreeClassifier(max_depth=2)
dt_clf.fit(x_train, y_train)
DTPrediction=dt_clf.predict(x_test)


940

In [39]:
y_true = y_test         
y_pred = DTPrediction   
#create confusion_matrix
print(confusion_matrix(y_true, y_pred))

# create classes for classification
target_names = ['class 0','class 1','class 2','class 3','class 4','class 5']
#report the classification parameter 
print(classification_report(y_true, y_pred, target_names=target_names))
# computing Train Accuracy and Test Accuracy 
print(f'Train Accuracy : {regr_clf.score(x_train,y_train):3f}')
print(f'Test Accuracy : {regr_clf.score(x_test,y_test):3f}')

[[114   0   0  30   1  11]
 [123   0   0  41   0   0]
 [ 52   0   0 105   0   0]
 [  7   0   0 118  14   7]
 [  0   0   0  95  26  26]
 [  2   0   0  10  11 147]]
              precision    recall  f1-score   support

     class 0       0.38      0.73      0.50       156
     class 1       0.00      0.00      0.00       164
     class 2       0.00      0.00      0.00       157
     class 3       0.30      0.81      0.43       146
     class 4       0.50      0.18      0.26       147
     class 5       0.77      0.86      0.81       170

    accuracy                           0.43       940
   macro avg       0.32      0.43      0.34       940
weighted avg       0.33      0.43      0.34       940

Train Accuracy : 0.454223
Test Accuracy : 0.430851
/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_div

In [41]:
tuned_parameters = {
    'splitter': ["best", "random"],
    'criterion': ["gini", "entropy"],
    'max_depth': [0,None],
    
}

In [42]:
dt_clf=DecisionTreeClassifier() # create classifier
# estimate the best set of hyper-parameter
dt_cv= GridSearchCV(regr_clf,tuned_parameters, cv=3) 

dt_cv.fit(x_train, y_train)
dt_cv.best_estimator_

/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 286, in fit
    raise ValueError("max_depth must be greater than zero. ")
ValueError: max_depth must be greater than zero. 

  warnings.warn("Estimator fit failed. The score on this train-test"
/home/parham/Desktop/project/Housing/env/lib/python3.8/site-packages/sklearn/model_se

DecisionTreeClassifier(criterion='entropy')

In [43]:
dt_clf= DecisionTreeClassifier(criterion='entropy')
dt_clf.fit(x_train, y_train)
DTPrediction=regr_clf.predict(x_test)


In [44]:
y_true = y_test         
y_pred = DTPrediction   
#create confusion_matrix
print(confusion_matrix(y_true, y_pred))

# create classes for classification
target_names = ['class 0','class 1','class 2','class 3','class 4','class 5']
#report the classification parameter 
print(classification_report(y_true, y_pred, target_names=target_names))
# computing Train Accuracy and Test Accuracy 
print(f'Train Accuracy : {dt_clf.score(x_train,y_train):3f}')
print(f'Test Accuracy : {dt_clf.score(x_test,y_test):3f}')

[[101  21   8   7   5  14]
 [ 32 102  24   5   1   0]
 [  6  19 106  22   4   0]
 [  3   4  20 101  17   1]
 [  2   0   6  14 115  10]
 [  4   0   1   0  22 143]]
              precision    recall  f1-score   support

     class 0       0.68      0.65      0.66       156
     class 1       0.70      0.62      0.66       164
     class 2       0.64      0.68      0.66       157
     class 3       0.68      0.69      0.68       146
     class 4       0.70      0.78      0.74       147
     class 5       0.85      0.84      0.85       170

    accuracy                           0.71       940
   macro avg       0.71      0.71      0.71       940
weighted avg       0.71      0.71      0.71       940

Train Accuracy : 0.969127
Test Accuracy : 0.710638


In [38]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score 
dt_clf= DecisionTreeClassifier(criterion='entropy')
scores = cross_val_score(dt_clf, x_train, y_train, cv=3)

print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.69 (+/- 0.01)
